bees/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from login.views import login, logout, register
from news.views import index, column_detail, article_detail, uploadImg, showImg
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('login/', login),
    path('register/',register),
    path('logout/', logout),
    path('captcha', include('captcha.urls')),
    path('column/<slug:column_slug>/', column_detail, name='column'),
    path('article/<pk>/<article_slug>', article_detail, name='article'),
    path('uploadImg/', uploadImg),
    path('showImg/', showImg),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

login/models.py
from django.db import models

# Create your models here.

class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField(max_length=128, unique= True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique= True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    creat_time = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-creat_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

news/models.py
from django.db import models
from login.models import User
from django.urls import reverse
from unidecode import unidecode
from django.template.defaultfilters import slugify

# Create your models here.

#栏目
class Column(models.Model):
    name = models.CharField('栏目名称', max_length=128)
    slug = models.CharField('栏目网址', max_length=256, db_index=True)
    intro = models.TextField('栏目简介', default='')

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('column',args=(self.slug,))

    class Meta:
        verbose_name = '栏目'
        verbose_name_plural = '栏目'
        ordering = ['name']



#文章
class Article(models.Model):
    column = models.ManyToManyField(Column, verbose_name='归属栏目')
    title = models.CharField('标题', max_length=256)
    slug = models.SlugField('slug', max_length=60, blank=True)
    author = models.ForeignKey(User, blank=True, null=True, verbose_name='作者', on_delete=models.CASCADE)
    #photo = models.URLField(blank=True)
    photo = models.ImageField(upload_to='images', null=True)
    content = models.TextField('内容', default='', blank=True)

    pub_date = models.DateTimeField('发表时间', auto_now_add=True, editable=True)
    update_time = models.DateTimeField('更新时间', auto_now=True, null=True)
    published = models.BooleanField('正式发布', default=True)

    def __str__(self):
        return self.title

    #当id或slug为空时，利用unidecode对中文解码，利用slugify方法根据标题手动生成slug
    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(unidecode(self.title))

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article', args=(self.pk, self.slug))

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'

#上传图片
class Img(models.Model):
    img_url = models.ImageField(upload_to='images')

login/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128)
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput)
    captcha = CaptchaField(label="验证码")


class RegisterForm(forms.Form):
    gender =(
        ('male',"男"),
        ('female',"女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput)
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput)
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput)
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput)
    sex = forms.ChoiceField(label="性别", choices=gender)
    captcha = CaptchaField(label='验证码')

login/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from login import models
from login import forms

# Create your views here.


def login(request):
    if request.session.get('is_login', None):
        return redirect("//")
    if request.method == "POST":
        login_form = forms.UserForm(request.POST)
        message = "请检查填写的内容！"

        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            try:
                user = models.User.objects.get(name=username)
                if user.password == password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('/index/')
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'login/login.html', locals())

    #对于非POST方法发送数据时，返回空表单，让用户可以填入数据
    login_form = forms.UserForm()
    return render(request, 'login/login.html', locals())

def register(request):
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == "POST":
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:
                    message = "用户名已存在，请重新选择用户名！"
                    return render(request, 'login/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:
                    message = "该邮箱地址已被注册，请使用别的邮箱！"
                    return render(request, 'login/register.html', locals())

                new_user = models.User()
                new_user.name = username
                new_user.password = password1
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                return redirect('/login/')

    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())



def logout(request):
    if not request.session.get('is_login', None):
        return redirect("/index/")
    request.session.flush()

    return redirect("/index/")

news/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from news.models import Column, Article, Img


# Create your views here.
def index(request):
    columns = Column.objects.all()
    article = Article.objects.all()
    imgs = Img.objects.all()

    context = {
        'article': article,
        'imgs': imgs
    }

    return render(request, 'index.html', context)

def column_detail(request, column_slug):
    column = Column.objects.get(slug=column_slug)
    return render(request, 'news/column.html', {'column': column})


def article_detail(request, pk, article_slug):
    article = Article.objects.get(pk=pk)

    #访问的文章地址与现在的文章地址不一样时，重定向（301）跳转到新的地址
    if article_slug != article.slug:
        return redirect(article, permanent=True)

    return render(request, 'news/article.html', {'article': article})


def uploadImg(request):
    if request.method == 'POST':
        img = Img(img_url = request.FILES.get('img'))
        img.save()
    return render(request, 'news/imgUpload.html')

def showImg(request):
    imgs = Img.objects.all()

    return render(request, 'index.html', {'imgs' : imgs})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

     <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <script src="{% static 'semantic/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'semantic/semantic.min.js'%}"></script>
    <script src="{% static 'js/home.js' %}"></script>

    {% block css %}{% endblock %}
</head>
<body>
<!-- Following Menu -->
<div class="ui inverted large top fixed hidden menu">
  <div class="ui container">

    <a class="active item" href="/">首页</a>
    <a class="item" href="/column/bee/">蜜蜂智慧</a>
    <a class="item" href="/column/new/">新闻动态</a>
    <div class="right menu">
      {% if request.session.is_login %}
        <div class="item">
            <a class="ui item">当前在线：{{ request.session.user_name }}</a>
        </div>
        <div class="item">
            <a href="/logout/">登出</a>
        </div>
       {% else %}
          <div class="item">
            <a href="/login/">登录</a>
        </div>
          <div class="item">
            <a href="/register/">注册</a>
        </div>
        {% endif %}
    </div>
  </div>
</div>
<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
    <a class="active item" href="/">首页</a>
    <a class="item" href="/column/bee/">蜜蜂智慧</a>
    <a class="item" href="/column/new/">新闻动态</a>

    {% if request.session.is_login %}
        <a class="item">当前在线：{{ request.session.user_name }}</a>
        <a href="/logout/">登出</a>
    {% else %}
        <a class="item" href="/login/">登录</a>
        <a class="item" href="/register/">注册</a>
    {% endif %}
</div>
<div class="pusher">

{% block content %}{% endblock %}

</div>
<!-- 页脚 -->
<div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
  </div>

</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block content %}

<!-- banner -->
<div class="banner_area">
    <div class="ui vertical masthead center aligned segment">

        <div class="ui container">
            <div class="ui large inverted secondary  menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="active item" href="/">首页</a>
                <a class="item" href="/column/bee/">蜜蜂智慧</a>
                <a class="item" href="/column/new/">新闻动态</a>
                <div class="right menu">
                    {% if request.session.is_login %}
                        <div class="item">
                            <a class="ui item">当前在线：{{ request.session.user_name }}</a>
                        </div>
                        <div class="item">
                            <a href="/logout/">登出</a>
                        </div>
                    {% else %}
                        <div class="item">
                            <a href="/login/">登录</a>
                        </div>
                        <div class="item">
                            <a href="/register/">注册</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="ui text container">

            <h1 class="ui inverted header">
                容县灵山梅花蜂场
            </h1>
            <h2 class="ui inverted header">原生态，纯天然，无污染，无加工，深山蜜蜂养殖</h2>

        </div>

    </div>
</div>
<!-- end banner -->

<!-- 内容 -->
    <div class="ui vertical stripe segment">
        <div class="ui middle aligned stackable grid container">
            <div class="row">
                <div class="eight wide column">

                    {% for articles in article %}
                        <div class="ui header">{{ articles.title }}</div>
                        <p>{{ articles.content|truncatewords:10 }}</p>
                    {% endfor %}
                </div>
                <div class="six wide right floated column">
                    <img src="/static/images/img3.jpg" class="ui fluid large bordered rounded image">
                </div>
        </div>

    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled  grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="/static/images/img1.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe segment">

<div class="ui four column grid">
    {% for item in imgs %}

        <div class="column">
            <div class="ui fluid card">
                <div class="image">
                    <img src="{{ item.img_url.url }}">
                </div>
                <div class="content">
                    <a class="header">{{ item.id }}</a>
                </div>
            </div>
        </div>
    {% endfor %}


</div>

    </div>





{% endblock %}

templates/login/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block content %}

    {% if request.session.is_login %}
        <h1>你好，{{ request.session.user_name }}!欢迎回来！</h1>
    {% else %}
        <h1>你尚未登录，只能访问公开内容！</h1>
    {% endif %}
{% endblock %}

templates/login/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}<link href="{% static 'css/login.css' %}" rel="stylesheet" />{% endblock %}


{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <h2 class="ui teal image header">
                <div class="content">欢迎登录</div>
            </h2>
            <form class="ui large form" action="/login/" method="post">
                {% csrf_token %}

                <div class="ui stacked segment">
                    <div class="field">
                         <div class="ui left icon input">
                            <i class="user icon"></i>

                                {{ login_form.username }}
                         </div>
                    </div>
                    <div class="field">
                         <div class="ui left icon input">
                            <i class="lock icon"></i>

                                {{ login_form.password }}
                         </div>
                    </div>

                    <div class="field">
                         <div class="ui left icon input">
                             {{ login_form.captcha.errors}}
                             {{ login_form.captcha.label_tag }}
                             {{ login_form.captcha }}
                         </div>
                    </div>

                    </div>




                    <button type="reset" class="ui teal submit button">重置</button>
                    <button type="submit" class="ui teal submit button">提交</button>



            </form>

            <div class="ui message">
                <p>
                {% if message %}
                    <div class="ui error message">{{ message }}</div>
                {% endif %}
                </p>
                <p>没有账号? <a href="#">注册</a></p>
            </div>
        </div>
    </div>
{% endblock %}

templates/login/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block content %}

<div class="ui segment container">
    <form class="ui form" action="/register/" method="post">

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        {% csrf_token %}
        <h2>欢迎注册</h2>

        <div class="field">
            {{ register_form.username.label_tag }}
            {{ register_form.username }}
        </div>

        <div class="field">
            {{ register_form.password1.label_tag }}
            {{ register_form.password1 }}
        </div>

        <div class="field">
            {{ register_form.password2.label_tag }}
            {{ register_form.password2 }}
        </div>

        <div class="field">
            {{ register_form.email.label_tag }}
            {{ register_form.email }}
        </div>

        <div class="field">
            {{ register_form.sex.label_tag }}
            {{ register_form.sex }}
        </div>

        <div class="field">
            {{ register_form.captcha.errors }}
            {{ register_form.captcha.label_tag }}
            {{ register_form.captcha }}
        </div>

        <button class="ui button" type="reset">重置</button>
        <button class="ui button" type="submit">提交</button>


    </form>


</div>

{% endblock %}

templates/news/article.html
{% extends 'base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}

<div class="banner_area">
    <div class="ui vertical masthead masthead_page center aligned segment">
        <div class="ui container">
            <div class="ui inverted large secondary menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="item" href="/">首页</a>
                <a class="item" href="/column/bee/">蜜蜂智慧</a>
                <a class="item" href="/column/new/">新闻动态</a>
                <div class="right menu">
                    {% if request.session.is_login %}
                        <div class="item">
                            <a class="ui item">当前在线：{{ request.session.user_name }}</a>
                        </div>
                        <div class="item">
                            <a href="/logout/">登出</a>
                        </div>
                    {% else %}
                        <div class="item">
                            <a href="/login/">登录</a>
                        </div>
                        <div class="item">
                            <a href="/register/">注册</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

 <div class="ui main text container">
    <h1 class="ui header">{{ article.title }}</h1>
    <p>This example shows how to use lazy loaded images, a sticky menu, and a simple text container</p>
  </div>
  <div class="ui text container">
  {% if article.photo %}
        <img src="{{ article.photo.url }}" alt="">
    {% else %}
        无图片
    {% endif %}
      <p>{{ article.content }}</p>
  </div>


{% endblock %}

templates/news/column.html
{% extends 'base.html' %}
{% block title %}栏目{% endblock %}
{% block content %}
    <!-- Page Contents -->
    <div class="banner_area">
    <div class="ui vertical masthead masthead_page center aligned segment">
        <div class="ui container">
            <div class="ui inverted large secondary menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="item" href="/">首页</a>
                <a class="item" href="/column/bee/">蜜蜂智慧</a>
                <a class="item" href="/column/new/">新闻动态</a>
                <div class="right menu">
                    {% if request.session.is_login %}
                        <div class="item">
                            <a class="ui item">当前在线：{{ request.session.user_name }}</a>
                        </div>
                        <div class="item">
                            <a href="/logout/">登出</a>
                        </div>
                    {% else %}
                        <div class="item">
                            <a href="/login/">登录</a>
                        </div>
                        <div class="item">
                            <a href="/register/">注册</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
    <p>栏目名称：{{ column.name }}</p>
    <p>栏目简介：{{ column.intro }}</p>
    <div>栏目文章列表：
    <ul>
        {% for article in column.article_set.all %}
            <li>
                <a href="{{ article.get_absolute_url }}"> {{ article.title }}</a>
            </li>
        {% endfor %}
    </ul>
    </div>

{% endblock %}

templates/news/imgUpload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图片上传</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="img">
        <input type="submit" value="上传">
    </form>
</body>
</html>

templates/news/showImg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图片展示</title>

</head>
<body>
    {% for item in imgs %}
        <img src="{{ item.img_url.url }}"><br/>
    {% endfor %}
</body>
</html>